### ISSUE TITLE
Prevent System exit from optional Step Failure

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/ocr-pipeline#13]
Currently, if the optional Quality Estimation encounters ALTO-XML missing textual contents, the Pipeline raises an custom Exception (which is quite okay, since there are no text lines that can be used for quality estimation) that leads to a hard-coded system exit. If this happens, no new Images are taken to the process pool. After finishing the last enqueued image, the pipeline stops.

Obviously, it is not wanted behavior, that empty optional data originating from a single image breaks the complete pipeline.

**Comment by adendogo** [comment]
After some tests it seems to be ok removing the _exit(1)_  call.
Therewith we'll close this issue.
