### ISSUE TITLE
Flag for DPI on command line

### ISSUE THREAD

**Issue by M3ssman** [ulb-sachsen-anhalt/ocr-pipeline#9]
While moving the DPI parameter from cli to configuration seemed to be a good solution at first, it turns out to be more convenient to provide the possibility to pass this again via cli at script execution time.

This means, that the default configured value for DPI can be overridden at execution time without the need to map a custom configuration for each built container image, since this requires to have individual container images for each required DPI.

**Comment by adendogo** [comment]
done, with recently merged branch **feature/dpi-arg**

**Comment by M3ssman** [comment]
dpi flag is propagated and can be injected from wrapper processes
